# Intro to Numpy

Numpy arrays can run quicker than standard python as they run at C level.

In [1]:
import numpy as np

In [2]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

#### Convert list into a numpy array

In [3]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [4]:
print(type(list1))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


#### Creating array without a list first

In [5]:
arr2 = np.arange(10, 21, 2)  #Start, stop, step
arr2

array([10, 12, 14, 16, 18, 20])

#### Multidimensional arrays

##### Can be created by connecting two lists

In [6]:
list2 = [40, 50, 60]
list2

[40, 50, 60]

In [7]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [8]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
arr3.shape

(2, 3)

In [10]:
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[2,3,4]]])
arr4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [2, 3, 4]]])

In [12]:
arr4.shape  # 3 dimensions - 3 items - 2 elements - 2 lists?????

(2, 2, 3)

### Lets go back to list 1

In [16]:
list1 * 3  # Will just triple up the lists

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [17]:
arr1 * 3  # Kinda like matrix multiplication

array([30, 60, 90])

### Mkae list 2 into array 2 to practice some multiplication

In [18]:
arr2 = np.array(list2)
arr2

array([40, 50, 60])

In [22]:
print(arr1)
print(arr2)

[10 20 30]
[40 50 60]


In [24]:
arr1 * arr2  # Element by element multiplication (broadcasting) - star operator
             # Broadcasting has to have same shape matrix

array([ 400, 1000, 1800])

In [25]:
arr1 * arr4

array([[[ 10,  40,  90],
        [ 40, 100, 180]],

       [[ 70, 160, 270],
        [ 20,  60, 120]]])

##### Create ndarrays of the following sizes:
- One dimensional array with 12 elements (12,)
- Two dimensional array size (3, 4)
- Three dimensional array size (2, 5, 4) (1 array consiting of 2 lists containing 5 lists that each contain 4 entries)
- Check the size of your array to make sure its correct

In [29]:
oned = np.array([1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45])
oned.shape

(12,)

In [32]:
twod = np.array([[1,2,3,4],
               [3,2,1,4],
               [4,5,6,8]])
twod.shape

(3, 4)

In [34]:
threed = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]],
                   [[6,7,8,9],[6,7,8,9],[6,7,8,9],[6,7,8,9],[6,7,8,9]]])
threed.shape

(2, 5, 4)

## Accessing Arrays

In [35]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [38]:
arr3[1][2]
# same as
arr3[1, 2]

60

In [39]:
arr3[1]

array([40, 50, 60])

In [40]:
arr3[1, :]

array([40, 50, 60])

In [41]:
arr3[:, 1]  # Vertical slice???

array([20, 50])

In [42]:
arr3.sum()  #sums all values in array

210

In [43]:
arr3.sum(0) #sums columnwise

array([50, 70, 90])

In [44]:
arr3.sum(1) # sums rowwise

array([ 60, 150])

In [45]:
arr3.mean() #loads of different ones

35.0

## iterate over arrays

In [46]:
arr1

array([10, 20, 30])

In [47]:
for x in arr3:
    print(x)

[10 20 30]
[40 50 60]


In [52]:
for x in arr3:
    for i in x:
        print(i)

10
20
30
40
50
60


In [54]:
for x in np.nditer(arr4):
    print(x)

1
2
3
4
5
6
7
8
9
2
3
4
